package com.huashe.pizz.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huashe.pizz.bean.ModuleProduct.ModuleProductBean;
import com.huashe.pizz.bean.ModuleProduct.ModuleProductMenu;
import com.huashe.pizz.bean.AboutUs.AboutUsBean;
import com.huashe.pizz.bean.HallCase.HallCaseMenu;
import com.huashe.pizz.bean.HallCase.HallCaseBean;
import com.huashe.pizz.bean.PersonalCenter.DataBean;

import com.huashe.pizz.bean.greendao.ModuleProductBeanDao;
import com.huashe.pizz.bean.greendao.ModuleProductMenuDao;
import com.huashe.pizz.bean.greendao.AboutUsBeanDao;
import com.huashe.pizz.bean.greendao.HallCaseMenuDao;
import com.huashe.pizz.bean.greendao.HallCaseBeanDao;
import com.huashe.pizz.bean.greendao.DataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig moduleProductBeanDaoConfig;
    private final DaoConfig moduleProductMenuDaoConfig;
    private final DaoConfig aboutUsBeanDaoConfig;
    private final DaoConfig hallCaseMenuDaoConfig;
    private final DaoConfig hallCaseBeanDaoConfig;
    private final DaoConfig dataBeanDaoConfig;

    private final ModuleProductBeanDao moduleProductBeanDao;
    private final ModuleProductMenuDao moduleProductMenuDao;
    private final AboutUsBeanDao aboutUsBeanDao;
    private final HallCaseMenuDao hallCaseMenuDao;
    private final HallCaseBeanDao hallCaseBeanDao;
    private final DataBeanDao dataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        moduleProductBeanDaoConfig = daoConfigMap.get(ModuleProductBeanDao.class).clone();
        moduleProductBeanDaoConfig.initIdentityScope(type);

        moduleProductMenuDaoConfig = daoConfigMap.get(ModuleProductMenuDao.class).clone();
        moduleProductMenuDaoConfig.initIdentityScope(type);

        aboutUsBeanDaoConfig = daoConfigMap.get(AboutUsBeanDao.class).clone();
        aboutUsBeanDaoConfig.initIdentityScope(type);

        hallCaseMenuDaoConfig = daoConfigMap.get(HallCaseMenuDao.class).clone();
        hallCaseMenuDaoConfig.initIdentityScope(type);

        hallCaseBeanDaoConfig = daoConfigMap.get(HallCaseBeanDao.class).clone();
        hallCaseBeanDaoConfig.initIdentityScope(type);

        dataBeanDaoConfig = daoConfigMap.get(DataBeanDao.class).clone();
        dataBeanDaoConfig.initIdentityScope(type);

        moduleProductBeanDao = new ModuleProductBeanDao(moduleProductBeanDaoConfig, this);
        moduleProductMenuDao = new ModuleProductMenuDao(moduleProductMenuDaoConfig, this);
        aboutUsBeanDao = new AboutUsBeanDao(aboutUsBeanDaoConfig, this);
        hallCaseMenuDao = new HallCaseMenuDao(hallCaseMenuDaoConfig, this);
        hallCaseBeanDao = new HallCaseBeanDao(hallCaseBeanDaoConfig, this);
        dataBeanDao = new DataBeanDao(dataBeanDaoConfig, this);

        registerDao(ModuleProductBean.class, moduleProductBeanDao);
        registerDao(ModuleProductMenu.class, moduleProductMenuDao);
        registerDao(AboutUsBean.class, aboutUsBeanDao);
        registerDao(HallCaseMenu.class, hallCaseMenuDao);
        registerDao(HallCaseBean.class, hallCaseBeanDao);
        registerDao(DataBean.class, dataBeanDao);
    }
    
    public void clear() {
        moduleProductBeanDaoConfig.clearIdentityScope();
        moduleProductMenuDaoConfig.clearIdentityScope();
        aboutUsBeanDaoConfig.clearIdentityScope();
        hallCaseMenuDaoConfig.clearIdentityScope();
        hallCaseBeanDaoConfig.clearIdentityScope();
        dataBeanDaoConfig.clearIdentityScope();
    }

    public ModuleProductBeanDao getModuleProductBeanDao() {
        return moduleProductBeanDao;
    }

    public ModuleProductMenuDao getModuleProductMenuDao() {
        return moduleProductMenuDao;
    }

    public AboutUsBeanDao getAboutUsBeanDao() {
        return aboutUsBeanDao;
    }

    public HallCaseMenuDao getHallCaseMenuDao() {
        return hallCaseMenuDao;
    }

    public HallCaseBeanDao getHallCaseBeanDao() {
        return hallCaseBeanDao;
    }

    public DataBeanDao getDataBeanDao() {
        return dataBeanDao;
    }

}
