package com.huashe.pizz.bean.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.huashe.pizz.bean.HallCase.HallCaseMenu;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "hallcasemenu".
*/
public class HallCaseMenuDao extends AbstractDao<HallCaseMenu, String> {

    public static final String TABLENAME = "hallcasemenu";

    /**
     * Properties of entity HallCaseMenu.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Icon1 = new Property(2, String.class, "icon1", false, "ICON1");
        public final static Property Icon2 = new Property(3, String.class, "icon2", false, "ICON2");
        public final static Property Parentid = new Property(4, String.class, "parentid", false, "PARENTID");
    }

    private DaoSession daoSession;


    public HallCaseMenuDao(DaoConfig config) {
        super(config);
    }
    
    public HallCaseMenuDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"hallcasemenu\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"ICON1\" TEXT," + // 2: icon1
                "\"ICON2\" TEXT," + // 3: icon2
                "\"PARENTID\" TEXT);"); // 4: parentid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"hallcasemenu\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HallCaseMenu entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String icon1 = entity.getIcon1();
        if (icon1 != null) {
            stmt.bindString(3, icon1);
        }
 
        String icon2 = entity.getIcon2();
        if (icon2 != null) {
            stmt.bindString(4, icon2);
        }
 
        String parentid = entity.getParentid();
        if (parentid != null) {
            stmt.bindString(5, parentid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HallCaseMenu entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String icon1 = entity.getIcon1();
        if (icon1 != null) {
            stmt.bindString(3, icon1);
        }
 
        String icon2 = entity.getIcon2();
        if (icon2 != null) {
            stmt.bindString(4, icon2);
        }
 
        String parentid = entity.getParentid();
        if (parentid != null) {
            stmt.bindString(5, parentid);
        }
    }

    @Override
    protected final void attachEntity(HallCaseMenu entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public HallCaseMenu readEntity(Cursor cursor, int offset) {
        HallCaseMenu entity = new HallCaseMenu( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // icon1
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // icon2
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // parentid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HallCaseMenu entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIcon1(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIcon2(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setParentid(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final String updateKeyAfterInsert(HallCaseMenu entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(HallCaseMenu entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HallCaseMenu entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
